# Generated by Django 5.1.15 on 2026-06-09 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.CharField(help_text='Chemin relatif du fichier MP3 stocké', max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('title', models.CharField(default='Sans titre', max_length=255)),
                ('artist', models.CharField(default='Inconnu', max_length=255)),
                ('album', models.CharField(blank=True, default='', max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.FloatField(default=0.0, help_text='Durée en secondes')),
                ('file_size', models.IntegerField(default=0, help_text='Taille en bytes')),
                ('file_hash', models.CharField(help_text='SHA256 du fichier pour détection de doublons', max_length=64, null=True, unique=True)),
                ('metadata_complete', models.BooleanField(default=False, help_text="True si l'extraction automatique a trouvé tous les champs")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Piste',
                'verbose_name_plural': 'Pistes',
                'ordering': ['-created_at'],
            },
        ),
    ]
